Fix warning due to mismatched popen()/pclose()
Compiler output:

mkPatch.c: In function 'CheckForTool':
mkPatch.c:872:5: error: 'fclose' called on pointer returned from a mismatched allocation function [-Werror=mismatched-dealloc]
  872 |     fclose( fdPtr );
      |     ^~~~~~~~~~~~~~~
mkPatch.c:865:13: note: returned from 'popen'
  865 |     fdPtr = popen( toolPath, "r" );
      |             ^~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

The warning was emitted by gcc-11.4.0. According to `man popen`:
 > The return value from popen() is a normal standard I/O stream in all
 > respects save that it must be closed with pclose() rather than
 > fclose(3).
Resolves: LE-16978
Change-Id: I12eb3097ed4014d4547fed745992e87fbee642c8