[DCS] Fix build error with gcc 8.3
With gcc 8.3.0:

dcsDaemon/dcsServer.c:264:9: error: 'strncpy' specified bound 32 equals destination size [-Werror=stringop-truncation]
         strncpy(DataChannelName, channelName, LE_DCS_CHANNEL_NAME_MAX_LEN);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

This issue can cause DataChannelName to not be null-terminated.

Resolves: LE-12749
Change-Id: I552da7cc9e0075224539ccc6683f4df8f17f15d3