[docker] Fix QEmu build with Alpine
The recent change from alpine:latest to 3.11 breaks two things:
- py-sphinx package is not available anymore
- qemu build fails with:
  error: ‘__SNR_ppoll’ undeclared here

Resolves: LE-14268
Change-Id: Iaf122dd72dcc1b42ef42c9925fb461a81e9df09b