Fix compiler warning relating to unnecessary copy
Compiler output:

FAILED: /data/legato/build/tools/obj/mkTools/codeGenerator/exeMainGenerator.cpp.o
g++ -std=c++0x -MMD -MF /data/legato/build/tools/obj/mkTools/codeGenerator/exeMainGenerator.cpp.o.d  -g -Wall -Werror -Wno-unused-command-line-argument -Wno-deprecated -I/data/legato/build/tools/precompiled/ -I/data/legato/framework/tools/defTools -I/data/legato/framework/tools/mkTools -I/data/legato/framework/liblegato -c /data/legato/framework/tools/mkTools/codeGenerator/exeMainGenerator.cpp -o /data/legato/build/tools/obj/mkTools/codeGenerator/exeMainGenerator.cpp.o
/data/legato/framework/tools/mkTools/codeGenerator/exeMainGenerator.cpp: In function 'void code::GenerateCLangExeMain(const model::Exe_t*, const mk::BuildParams_t&)':
/data/legato/framework/tools/mkTools/codeGenerator/exeMainGenerator.cpp:171:25: error: loop variable 'fileSystemObjectPtr' creates a copy from type 'const std::shared_ptr<model::FileSystemObject_t>' [-Werror=range-loop-construct]
  171 |         for (const auto fileSystemObjectPtr : componentPtr->bundledFiles)
      |                         ^~~~~~~~~~~~~~~~~~~
/data/legato/framework/tools/mkTools/codeGenerator/exeMainGenerator.cpp:171:25: note: use reference type to prevent copying
  171 |         for (const auto fileSystemObjectPtr : componentPtr->bundledFiles)
      |                         ^~~~~~~~~~~~~~~~~~~
      |

This warning was emitted by gcc-11.4.0. There are two cases where
iterating over a collection of items by value rather than by reference
causes the value to need to be copied. This commit changes the iteration
to be by reference which prevents the copy and the warning from gcc.
Resolves: LE-16978
Change-Id: I4ab4672a80948b6da369b3e7f02841ba360e4878