[Test] Fix new compilation warnings by gcc-9.2
Fix the new compilation warnings raised by gcc-9.2 in Yocto-3.

E.g.:
  apps/test/smsInboxService/smsInboxServiceUnitTest/main.c:454:5: error:
    ‘strncat’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  454 |     strncat(cfgCpCommand, smsCfgFilePath, cfgFilePathLen + 1);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  apps/test/smsInboxService/smsInboxServiceUnitTest/main.c:453:29: note: length computed here
  453 |     size_t cfgFilePathLen = strlen(smsCfgFilePath);
      |                             ^~~~~~~~~~~~~~~~~~~~~~

These warnings arise from using strncat as a makeshift strcat, which
does not prevent buffer overflow. Replace with le_utf8_Append.

Resolves: LE-14421
Change-Id: Ia7e02ad43d5f09409503bafc2f753fdde4db5c8b
Signed-off-by: Anju Kunjumon <akunjumon@sierrawireless.com>